FROM node:22

# Install netcat for health checks and all required system dependencies
RUN apt-get update && apt-get install -y \
    netcat-openbsd \
    libnss3 \
    libatk-bridge2.0-0 \
    libxss1 \
    libasound2 \
    libxshmfence1 \
    libgbm1 \
    libgtk-3-0 \
    libx11-xcb1 \
    libdrm2 \
    libxcomposite1 \
    libxdamage1 \
    libxrandr2 \
    libpangocairo-1.0-0 \
    libcups2 \
    libatk1.0-0 \
    libx11-6 \
    libxext6 \
    libxfixes3 \
    libxcb1 \
    libglib2.0-0 \
    libpango-1.0-0 \
    libcurl4 \
    ffmpeg

# Set working directory
WORKDIR /app

# Copy dependency files
COPY package*.json ./

# Install project dependencies
RUN npm ci --legacy-peer-deps

# Install global dev tools
RUN npm install -g ts-node tsconfig-paths pm2

# Copy the rest of the project files
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Build the NestJS app
RUN npm run build


# Expose port
EXPOSE 3000

# Add startup script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
